name: Quirkademia
author: Simplicitee
api-version: 1.13
version: 1.0.0
main: me.simp.quirkademia.QuirkPlugin
commands:
  quirk:
    aliases: [q]
    usage: /<command>
permissions:
  quirk.user:
    default: true
    children:
      quirk.command.user: true
      quirk.command.help: true
      quirk.command.list: true
  quirk.admin:
    default: op
    children:
      quirk.command.user.set: true